### PR TITLE
Decaffeinate fixes

### PR DESCRIPTION
**Pull request by UziTech**
I cleaned up the code and added the `provideTerminal` method from #2 

I have manually tested everything on Windows 10 and it all seems to work.

### CODE REVIEW

**Comment by UziTech** [comment]
@the-j0k3r The issue that you mentioned in https://github.com/bus-stop/terminus/issues/1#issuecomment-552172667 about erroring when changing settings should be fixed as well. It was throwing an error because the functions were getting bound after initialize was called.

**Comment by the-j0k3r** [comment]
Thats fantastic news, all being well after a few tests then we should be good to go.

Thank you so much for this contribution. =) just bare with me while I test this out.

**Comment by the-j0k3r** [comment]
@UziTech This PR got me excited and I went around testing.

The Good:

Windows 10 passes all tests, works 100%.

The Bad

macOS this is not working at all, while caffeinated version does

The issue is terminal loads but you cant type, and this is specific to the JS version only.
Will need to test with Linux also.

There are no errors whatsoever.

Tested in virtualbox macOS Mojave

**Comment by UziTech** [comment]
The biggest issue is the way [space-pen](https://github.com/atom-archive/space-pen) handles extending a class. Probably why it is no longer maintained.

I'm going to try moving the views to [etch](https://github.com/atom/etch)

**Pull request merged**
