### PR TITLE
chore(travis): update config (deprecation/updates)

### PR DESCRIPTION
**Pull request by the-j0k3r**
To address this.

Capture

### CODE REVIEW

**Comment by the-j0k3r** [comment]
mmm to get rid of the missing OS messages it adds more jobs

Capture

How to solve like previous without these messages and adding extra jobs like

Capture

**Comment by the-j0k3r** [comment]
Done last commit seems to be it, I know its only info message but rather just comply cleanly.

**Comment by UziTech** [comment]
we could also move to github actions to keep windows, mac, and linux tests on the same service.

You would pretty much just need to copy [x-terminal/.github/workflows/main.yml](https://github.com/bus-stop/x-terminal/blob/master/.github/workflows/main.yml)

**Comment by UziTech** [comment]
Closing this since we are using actions

**Pull request closed without merging**
