### PR TITLE
Standard eslint

### PR DESCRIPTION
**Pull request by UziTech**
use [`standard`](https://standardjs.com/) config for eslint

### CODE REVIEW

**Comment by UziTech** [comment]
I added `npm run lint` to husky so it will run before push

**Comment by the-j0k3r** [comment]
We need to add a `standad --fix` script to package.json, no? to be run on pre push so all code automatically conforms to the style, right? linting only lints doesn't fix or change code.

Also about the `eslint --fix`, is that what that does it calls `standard --fix` or is that script no longer needed?

**Comment by UziTech** [comment]
`eslint . --fix` does the same thing as `standard --fix`. Standard just uses eslint under the hood

**Comment by the-j0k3r** [comment]
and about making the pre-commit hook a fix instead of prepush lint or prepush fix?

**Comment by UziTech** [comment]
I didn't want to make it on pre-commit since it lints all files not just the ones in the commit. I think pre-push is fine. Ideally their IDE will be alerting them of errors as they type but if not pre-push is just the catch all.

**Comment by the-j0k3r** [comment]
I was thinking,  if the existing code is already linted and fixed.... The only upside is not having to ask a user to run a fix script with their PR's right?

I thought the point of having a standard is so we dont review ugly code or ask users to run fix, which if the pre-existeing code is not linted/fixed we end up with a unrelated fixes anyway.

Doesnt make sense not to have it but I will redirect users to run the fix script with PR.s

**Comment by UziTech** [comment]
The pre-push hook runs before they push code to their PR branches so it shouldn't let them push code to PRs that fails linting.

**Pull request merged**
