### PR TITLE
add tests, eslint, and semantic release

### PR DESCRIPTION
**Pull request by UziTech**
- Add `atom-jasmine3-test-runner` to allow tests to use latest Jasmine instead of Atom's bundled Jasmine 1.3
- Add eslint
- Add semantic release
- Add [renovate](https://renovate.whitesourcesoftware.com/) configuration file

### CODE REVIEW

**Comment by UziTech** [comment]
I don't know what we want for eslint rules. I kept them minimal mostly using `eslint:recommended`.

If we want to use `semantic-release` we will need to set up travis ci and appveyor and add tokens to travis to allow semantic release to publish to apm and github releases

**Comment by the-j0k3r** [comment]
>I don't know what we want for eslint rules

it would be nice to auto-format with spaces instead of tabs that sort of thing.

>If we want to use semantic-release we will need to set up travis ci and appveyor and add tokens to travis to allow semantic release to publish to apm and github releases

I suppose this would replace `apm publish` in a way right? Could this be done with Actions rather than travis/ or AV you think? https://github.com/bus-stop/terminus/actions

Else setup of Travis or AV should also be OK in case not.

Whatever you think is best ;)

**Comment by UziTech** [comment]
> it would be nice to auto-format with spaces instead of tabs that sort of thing.

you can auto-format with `npm run lint -- --fix` otherwise `npm run lint` just tests to see if everything is formatted correctly.

I personally prefer tabs when working with multiple people on the same project so each person can set their own preference in their editor on number of character width for indentation (2, 4, 8, etc.). But it doesn't really matter that much. I just press the tab key and let my editor decide whether it should enter spaces or tabs.

> I suppose this would replace `apm publish`

Yes, `semantic-release` will replace the need to manually publish. It will automatically publish a new version based on the [commit messages](https://github.com/semantic-release/semantic-release#commit-message-format)

> Could this be done with Actions

It should be possible and there is a PR https://github.com/atom/ci/pull/100 to get it working but I haven't had any success with GitHub actions and apm yet.

**Comment by UziTech** [comment]
This also adds a configuration file for [`renovate`](https://renovate.whitesourcesoftware.com/) for dependency management but we could also use dependabot or something else

**Comment by the-j0k3r** [comment]
> This also adds a configuration file for [`renovate`](https://renovate.whitesourcesoftware.com/) for dependency management but we could also use dependabot or something else

I wouldnt go that far, just use https://www.npmjs.com/package/updates its enough `npm i updates --save-dev` then every so often we run the script

```json
  "scripts": {
    "update": "updates -cu && npm install"
```

It auto installs updates and makes a commit. seems fine, may even automate via action

**Comment by the-j0k3r** [comment]
I think we are ready to make decaffeinated-terminus the new master at this stage.

Barring any legacy bugs, this branch is working fine in Windows 10, macOS and Linux.

Give me the go ahead and Ill try to swap branches without killing this PR =)

**Comment by the-j0k3r** [comment]
OK @akonwi `decaffeinated-terminus` is now the new master, I'll wait till this PR is merged before renaming `decaffeinated-terminus` to master, else it will close the pull request.

**Comment by UziTech** [comment]
> all we need to worry about is running a lint + clean script every other Friday.

I would rather have things be automated instead of needing to manually run something. With `husky` we could have it run a script before every commit.

You can merge `decaffeinated-terminus` into `master` and I will rebase this on `master`. This PR was more or less to start the discussion about what things we want automated.

**Comment by the-j0k3r** [comment]
>You can merge decaffeinated-terminus into `master`

I cant the branches diverged somewhat and conflict galore here otherwise. Best at this stage is to rename branches.

Im not sure what that will do to existing clones though.

Ill go ahead with branch rename if this closes please resubmit.

> I would rather have things be automated instead of needing to manually run something. With `husky` we could have it run a script before every commit.

that would do also do, what about prettier? needed/not needed?

**Comment by UziTech** [comment]
I've never used prettier. I honestly don't know if there is a difference between `eslint --fix` and `prettier`

**Comment by the-j0k3r** [comment]
> I've never used prettier. I honestly don't know if there is a difference between `eslint --fix` and `prettier`

Theres probably not much in it, its more like an extension TBH, whatever is simplest.

Branches renaming done. All hell probably breaking loose right about now.

**Comment by akonwi** [comment]
Prettier is really great for formatting. Different from eslint because it's focused on those editor config things and supports json, stylesheets, and more, where as eslint targets coding style

**Comment by the-j0k3r** [comment]
And it also formats all hex to lowercase, like the hex colors on the less files which I used stylint locally to change this in https://github.com/bus-stop/terminus/commit/4013fecc705e128c238c9c39d1625ea35c79cd2f

I prefer lowercase so as not to confuse 8B with tired ol eyes

**Comment by UziTech** [comment]
> it's focused on those editor config things
@akonwi are you saying prettier formats the code based on user preferences not software preferences? Wouldn't that mess with git blame if the code is changing for each user?

**Comment by the-j0k3r** [comment]
>Wouldn't that mess with git blame if the code is changing for each user?

The project can carry .editorcofif files I think prettier respects that, else youre probably right

**Comment by akonwi** [comment]
> > it's focused on those editor config things
> 
> @akonwi are you saying prettier formats the code based on user preferences not software preferences? Wouldn't that mess with git blame if the code is changing for each user?

Prettier formats according to a standard for the whole project so the result is the same for everyone. As for git blame, I don't think prettier has anymore impact than eslint fixing.

**Comment by akonwi** [comment]
I just want to add that prettier and eslint aren't mutually exclusive either, I currently use both together professionally and personally.

**Comment by the-j0k3r** [comment]
@akonwi do you have any dot files anywhere with configs that can be adapted to this project?

Ide guess it would be prettier and prettier-eslint devdep requirement too.

**Pull request closed without merging**
